export const restaurants = [
    {
        name: "McDonald's",
        rating: 4.5,
        location: "Ramat Gan",
        priceLevel: "$-$$",
        image: require("./assets/4.png"),
        isVeganFriendly: false,
        isWheelchairAccessible: true,
        isGlutenFree: false,
        type: "fast-food",
        
    },
    {
        name: "Moon Sushi",
        rating: 4.7,
        location: "Tel Aviv, bograshov 58", 
        priceLevel: "$$-$$$",
        image: require("./assets/3.png"),
        isVeganFriendly: true,
        isWheelchairAccessible: true,
        isGlutenFree: true,
    },
    {
        name: "OCD",
        rating: 5,
        location: "Tel Aviv",
        priceLevel: "$$$-$$$$",
        image: require("./assets/2.png"),
        isVeganFriendly: true,
        isWheelchairAccessible: false,
        isGlutenFree: false,
    },
    {
        name: "Emesh",
        rating: 4.4,
        location: "Tel Aviv, lilinblum 30",
        priceLevel: "$$-$$$",
        image: require("./assets/1.png"),
        isVeganFriendly: true,
        isWheelchairAccessible: false,
        isGlutenFree: true,
    },
];