const DATABASE_NAME = "dishcover_db";
const COLLECTIONS = {
  RESTAURANTS_RAW: "restaurants_raw",
  RESTAURANTS: "restaurants",
  RESTAURANTS_REVIEW: "restaurants_review",
  USER_INFO: "user_info",
};

const cuisines = [
  "Israeli",
  "Italian",
  "Bar",
  "Asian",
  "Cafe",
  "Mediterranean",
  "American",
  "Fast Food",
  "European",
  "Seafood",
  "Grill",
  "Steakhouse",
  "South American",
  "Moroccan",
  "Russian",
  "Vegetarian Friendly",
  "Middle Eastern",
  "International",
  "Barbecue",
  "Mexican",
  "Pizza",
  "Japanese",
  "French",
  "Kosher",
  "Eastern European",
  "Healthy",
  "Greek",
  "Street Food",
  "Georgian",
  "Irish",
  "Sushi",
  "Fruit parlours",
  "Brew Pub",
  "Peruvian",
  "Turkish",
  "Diner",
  "Egyptian",
  "Caucasian",
  "Arabic",
  "Southwestern",
  "Pub",
  "British",
  "Persian",
  "Azerbaijani",
  "African",
  "Oceanic",
  "Lebanese",
  "Austrian",
];
const districts = [
  "Southern District",
  "Tel Aviv District",
  "Jerusalem District",
  "Central District",
];

module.exports = { DATABASE_NAME, COLLECTIONS };
